* Project 4 Sorting

* Due:Friday 4/14 7:00am (the day after the last day of Spring Break)

* Description

Start with the class code that implements the selection, merge, and
quick sorts.

Write a new version of quick sort, qsort2. It should have this
signature ~std::vector<int> qsort2(std::vector<int>, int low, int
high);~.

It should:

1. Use a reasonable pivot (as opposed to just list[0])
2. It should perform the sort *in place*, that is it should
   rearrange the elements in the vector around the pivot as opposed to
   copying to a new vector. It should then return itself.
3. When first calling, low should be 0 and high should be the last
   index in the input vector. In each recursive call, low and high
   should be modified to index in to the part of the vector you're
   recursively sorting.

Run some timing tests on data sets of different sizes and
configurations to compare the merge and quick sorts we wrote together
in class with your new sort. Also, run the C++ built in sort and
compare that as well (you'll have to look that one up).


Edit this file and add comments below indicating what you found when
you did your timing experiments. 

* Notes:

This assignment does not require doctest testing. It does, however
require a make file that compiles to an executable named *main*. You
can create a new Makefile or copy and modify one you've used in the past.


* Write your comments here:   

   Qsort 2 is extremely faster than all the other sorting methods. 
   When testing on vectors of size 10000,
   Selection sort had an elapsed time of 210
   Merge sort had an elapsed time of 28
   The orginal quick sort had an elapsed time of 31
   And my quick sort 2 had an elapsed time of 2.
   The built in sorting for c++ also had an elapsed time of 2,
   However sometimes quick sort 2 would be quicker and get an elapsed time of 1
   While the built in sort never did, at least for me
   
   My findings proved consistent when increasing the size to 100000
   In fact, selection sort took Way too long and I coudln't even get a time
   Merge sort had an elapsed time of 283
   original quick sort had an elapsed time of 1578
   And my quick sort 2 had an elapsed time of 15
   The built in sorting gave an elapsed time of 25
   Further showing how quick sort 2 is the quickest
   
   It's insane how much faster quick sort 2 is!
